all: mostrar_poema mostrar_poema_syscall

.c.o:
	$(CC) -o $@ $<

mostrar_poema: mostrar_poema.c


mostrar_poema_syscall: mostrar_poema_syscall.c


clean: 
	rm -f mostrar_poema mostrar_poema_syscall
	rm -f *~
